# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.network "private_network", ip: "192.168.10.21"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     # Workaround for a storage controller bug in Xenial:
     vb.customize [
        "storagectl", :id,
        "--name", "SATA Controller",
        "--hostiocache", "on"
     ]
  end

  # Workaround for a storage controller bug in Xenial:
  config.vm.provision :shell, inline: "echo 1 > /sys/block/sda/device/queue_depth"

  config.vm.hostname = "client"

  # Provision:
  config.vm.provision :shell, path: "vagrant/setup_client.sh"
  #config.vm.provision :shell, path: "vagrant/provision.sh"
  #config.vm.provision :shell, path: "vagrant/provision_user.sh", privileged: false

  # Startup:
  #config.vm.provision :shell, path: "vagrant/startup.sh", run: "always"
end

