{
 "title": "DemoDashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "pc_host",
    "label": "PC and Host (Client Stats)",
    "query": "SHOW TAG VALUES FROM \"client\" WITH KEY = \"pc_host\""
   },
   {
    "name": "HOST_DEV",
    "label": "PC and Device (Switch Stats)",
    "query": "SHOW TAG VALUES FROM \"ip.rx\" WITH KEY = \"host_dev\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h1>Client Stats</h1></center>"
  },
  {
   "title": "App Type of Client at \"$pc_host\"",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "client",
     "select": [
      [
       { "params": [ "app_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pc_host", "operator": "=~", "value": "/^$pc_host$/" }
     ]
    }
   ]
  },
  {
   "title": "App ID of Client at \"$pc_host\"",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "client",
     "select": [
      [
       { "params": [ "app_id" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pc_host", "operator": "=~", "value": "/^$pc_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Raw Application Metric of Client at \"$pc_host\"",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "client",
     "select": [
      [
       { "params": [ "raw_application_metric" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pc_host", "operator": "=~", "value": "/^$pc_host$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "content": "<center><h1>Interface Stats</h1></center>"
  },
  {
   "title": "Sent Datarate of $HOST_DEV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "ip.tx",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host_dev", "operator": "=~", "value": "/^$HOST_DEV$/" }
     ]
    }
   ]
  },
  {
   "title": "Received Datarate of $HOST_DEV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "ip.rx",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host_dev", "operator": "=~", "value": "/^$HOST_DEV$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "content": "<center><h1>Switch Stats</h1></center>"
  },
  {
   "title": "Sent Datarate eth2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "tc.sent",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "eth2" }
     ]
    }
   ]
  },
  {
   "title": "Sent Datarate eth3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "tc.sent",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "eth3" }
     ]
    }
   ]
  },
  {
   "title": "Dropped Bytes eth2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "tc.sent",
     "select": [
      [
       { "params": [ "dropped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "eth2" }
     ]
    }
   ]
  },
  {
   "title": "Dropped Bytes eth3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "tc.sent",
     "select": [
      [
       { "params": [ "dropped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "switch" },
      { "condition": "AND", "key": "dev", "operator": "=", "value": "eth3" }
     ]
    }
   ]
  },
  {
   "title": "Delay over Bottleneck",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}