# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/contrib-stretch64"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.10.11"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  # Provision:
  config.vm.provision :shell, path: "vagrant/provision.sh"
end

